apiVersion: apps/v1
kind: Deployment  
metadata:
  name: borrow
  labels:
    app: borrow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow
  template:
    metadata:
      labels:
        app: borrow
    spec:
      containers:
        - name: borrow
          image: minwoop/borrow:1
          ports:
            - containerPort: 8080
          readinessProbe: # 무정지 배포를 위한 readinessProbe 설정
            httpGet:
              path: '/borrows'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10